name: PR Validate

on:
  pull_request:
    branches:
      - main
      - "release/*"
  workflow_dispatch:

jobs:
  sdk-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: SDK Unit Tests
        run: ./gradlew :sdk:testDebugUnitTest :sdk:testReleaseUnitTest --stacktrace --no-daemon

      - name: SDK Publish Check (Maven Local)
        run: ./gradlew :sdk:publishToMavenLocal -x test --stacktrace --no-daemon
